---
title: "Perceived Grading and Student Evaluation of Instruction"
author: "Erin M. Buchanan"
date: "6/29/2017"
output: word_document
---

```{r setup, include=FALSE}
library(knitr)
library(papaja)
knitr::opts_chunk$set(echo = TRUE)
```

## Reliability of instructor scores across courses

```{r reliability-section, include=FALSE}
##import the file
#library(haven)
#master = read_spss("paired_correl.sav")
#names(master)

##delete double pairings
#cutout = duplicated(master[ , c(3:14, 46)])
#master = master[ cutout , ]
#reduceddata = write.csv(master, "paired_correl.csv", row.names = F)

##the section above was created from a non-identified dataset 
##the deidentified set is provided online and code starts here.
master = read.csv("paired_correl.csv")

##q1, q3, q4, q9, q15
##reverse coding of same columns, so that 1 = yes
master$SameCourse = 1 - master$SameCourse
master$SameSemester = 1 - master$SameSemester
master$SameCourseAndSemester = 1 - master$SameCourseAndSemester

table(master$SameSemester)
table(master$SameCourse)
table(master$SameCourseAndSemester)
table(master$SameSemester, master$SameCourse)
##for each combination calculate the paired correlation

nopairs = tapply(master$Q11, master$instructcode, length)
summary(nopairs)
mean(nopairs)
sd(nopairs)

#first is the semester, second course
diff_diff = subset(master, SameSemester == 0 & SameCourse == 0)
diff_same = subset(master, SameSemester == 0 & SameCourse == 1)
same_diff = subset(master, SameSemester == 1 & SameCourse == 0)
same_same = subset(master, SameSemester == 1 & SameCourse == 1)

##set up the analysis
library(nlme)

####diff diff####
dd1 = lme(Q11 ~ Q12 + NSemester1 + NSemester2, 
             data = diff_diff, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

dd3 = lme(Q31 ~ Q32, 
             data = diff_diff, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

dd4 = lme(Q41 ~ Q42, 
             data = diff_diff, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

dd9 = lme(Q91 ~ Q92, 
             data = diff_diff, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

dd15 = lme(Q151 ~ Q152, 
             data = diff_diff, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)
summary(dd1)
summary(dd3)
summary(dd4)
summary(dd9)
summary(dd15)

####diff same####
ds1 = lme(Q11 ~ Q12, 
             data = diff_same, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

ds3 = lme(Q31 ~ Q32, 
             data = diff_same, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

ds4 = lme(Q41 ~ Q42, 
             data = diff_same, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

ds9 = lme(Q91 ~ Q92, 
             data = diff_same, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

ds15 = lme(Q151 ~ Q152, 
             data = diff_same, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)
summary(ds1)
summary(ds3)
summary(ds4)
summary(ds9)
summary(ds15)

####same diff####
sd1 = lme(Q11 ~ Q12, 
             data = same_diff, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

sd3 = lme(Q31 ~ Q32, 
             data = same_diff, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

sd4 = lme(Q41 ~ Q42, 
             data = same_diff, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

sd9 = lme(Q91 ~ Q92, 
             data = same_diff, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

sd15 = lme(Q151 ~ Q152, 
             data = same_diff, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)
summary(sd1)
summary(sd3)
summary(sd4)
summary(sd9)
summary(sd15)

####same same####
ss1 = lme(Q11 ~ Q12, 
             data = same_same, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

ss3 = lme(Q31 ~ Q32, 
             data = same_same, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

ss4 = lme(Q41 ~ Q42, 
             data = same_same, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

ss9 = lme(Q91 ~ Q92, 
             data = same_same, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)

ss15 = lme(Q151 ~ Q152, 
             data = same_same, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)
summary(ss1)
summary(ss3)
summary(ss4)
summary(ss9)
summary(ss15)

####assumptions from mlm####
##rotated out models, all show the same results
##commented out to save processing time
##standardized1 = as.data.frame(scale(dd1$residuals))$fixed
##fitted = scale(fitted.values(dd1))

##Linearity
##{plot(qqnorm(standardized1))
##abline(0,1)}

##normality
##hist(standardized1)

##homog and s
##{plot(fitted,standardized1)
##abline(0,0)
##abline(v=0)}

```

## Tables for Reliability of Instructor Scores
```{r Table-1, echo=FALSE, results='asis'}
tableprint = matrix(NA, nrow = 20, ncol = 6)
colnames(tableprint) = c("Coefficient", "*b*", "*SE*", "*df*", "*t*", "*p*")

tableprint[1, ] = c("DD Overall", unname(round(summary(dd1)$tTable[-1, ], 3)))
tableprint[2, ] = c("DD Exams", unname(round(summary(dd3)$tTable[-1, ], 3)))
tableprint[3, ] = c("DD Fair", unname(round(summary(dd4)$tTable[-1, ], 3)))
tableprint[4, ] = c("DD Assignments", unname(round(summary(dd9)$tTable[-1, ], 3)))
tableprint[5, ] = c("DD Grade", unname(round(summary(dd15)$tTable[-1, ], 3)))

tableprint[6, ] = c("DS Overall", unname(round(summary(ds1)$tTable[-1, ], 3)))
tableprint[7, ] = c("DS Exams", unname(round(summary(ds3)$tTable[-1, ], 3)))
tableprint[8, ] = c("DS Fair", unname(round(summary(ds4)$tTable[-1, ], 3)))
tableprint[9, ] = c("DS Assignments", unname(round(summary(ds9)$tTable[-1, ], 3)))
tableprint[10, ] = c("DS Grade", unname(round(summary(ds15)$tTable[-1, ], 3)))

tableprint[11, ] = c("SD Overall", unname(round(summary(sd1)$tTable[-1, ], 3)))
tableprint[12, ] = c("SD Exams", unname(round(summary(sd3)$tTable[-1, ], 3)))
tableprint[13, ] = c("SD Fair", unname(round(summary(sd4)$tTable[-1, ], 3)))
tableprint[14, ] = c("SD Assignments", unname(round(summary(sd9)$tTable[-1, ], 3)))
tableprint[15, ] = c("SD Grade", unname(round(summary(sd15)$tTable[-1, ], 3)))

tableprint[16, ] = c("SS Overall", unname(round(summary(ss1)$tTable[-1, ], 3)))
tableprint[17, ] = c("SS Exams", unname(round(summary(ss3)$tTable[-1, ], 3)))
tableprint[18, ] = c("SS Fair", unname(round(summary(ss4)$tTable[-1, ], 3)))
tableprint[19, ] = c("SS Assignments", unname(round(summary(ss9)$tTable[-1, ], 3)))
tableprint[20, ] = c("SS Grade", unname(round(summary(ss15)$tTable[-1, ], 3)))

apa_table(tableprint,
          align = c("l", rep("c", 5)), 
          caption = "t Statistics for Reliability Correlations",
          note = "Letters indicate Different (D) and Same (S) distinction wherein the first letter is for semester and second letter is for course."
 )
```

```{r data-screening, include=FALSE}
#import the data
reliability = read.csv("reliability.csv")

####data screening####
##accuracy and missing data 
summary(reliability)
reliability$type = as.factor(reliability$type)
reliability$type = relevel(reliability$type, ref = "4")

##multicollinearity/additivity for med/mod analyses
correlation = cor(reliability[ , c(8, 22, 25)], use = "pairwise.complete.obs")
symnum(correlation)
correlation

##assumptions for med/mod analyses
random = rchisq(nrow(reliability), 7)
fake = lm(random ~ ., data = reliability[ , c(8, 22, 24, 25)])
fitted = scale(fake$fitted.values)
standardized = rstudent(fake)

##linearity
{plot(qqnorm(standardized))
abline(0,1)}

##normality
hist(standardized)

##homog / homos
{plot(fitted, standardized)
abline(0,0)
abline(v=0)}

##homogeneity and scedasticity problems
```

## Correlations between relevant evaluation items 
```{r correlations, include = FALSE}

##split the datasets by level
undergrad = subset(reliability, Course1 < 600)
grad = subset(reliability, Course1 >= 600)

library(nlme)

####all undergraduate courses####
#q1 to everything
q1.3 = lme(Q11 ~ Q31, 
           data = undergrad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q1.4 = lme(Q11 ~ Q41, 
           data = undergrad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q1.9 = lme(Q11 ~ Q91, 
           data = undergrad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q1.15 = lme(Q11 ~ Q151, 
           data = undergrad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

#3 to rest
q3.4 = lme(Q31 ~ Q41, 
           data = undergrad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q3.9 = lme(Q31 ~ Q91, 
           data = undergrad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q3.15 = lme(Q31 ~ Q151, 
           data = undergrad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

#q 4 to rest
q4.9 = lme(Q41 ~ Q91, 
           data = undergrad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q4.15 = lme(Q41 ~ Q151, 
           data = undergrad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

#q9 to rest
q9.15 = lme(Q91 ~ Q151, 
           data = undergrad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

####graduate courses####
q1.3c = lme(Q11 ~ Q31, 
           data = grad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q1.4c = lme(Q11 ~ Q41, 
           data = grad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q1.9c = lme(Q11 ~ Q91, 
           data = grad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q1.15c = lme(Q11 ~ Q151, 
           data = grad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

#3 to rest
q3.4c = lme(Q31 ~ Q41, 
           data = grad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q3.9c = lme(Q31 ~ Q91, 
           data = grad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q3.15c = lme(Q31 ~ Q151, 
           data = grad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

#q 4 to rest
q4.9c = lme(Q41 ~ Q91, 
           data = grad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

q4.15c = lme(Q41 ~ Q151, 
           data = grad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)

#q9 to rest
q9.15c = lme(Q91 ~ Q151, 
           data = grad, 
           method = "ML", 
           na.action = "na.omit",
           random = ~1|instructcode)
```

## Tables for Correlations Between Items 
```{r Table-2, echo=FALSE, results='asis'}
tableprint = matrix(NA, nrow = 20, ncol = 6)
colnames(tableprint) = c("Coefficient", "*b*", "*SE*", "*df*", "*t*", "*p*")

tableprint[1, ] = c("Overall to Exams", unname(round(summary(q1.3)$tTable[-1, ], 3)))
tableprint[2, ] = c("Overall to Fair", unname(round(summary(q1.4)$tTable[-1, ], 3)))
tableprint[3, ] = c("Overall to Assignments", unname(round(summary(q1.9)$tTable[-1, ], 3)))
tableprint[4, ] = c("Overall to Grade", unname(round(summary(q1.15)$tTable[-1, ], 3)))
tableprint[5, ] = c("Exams to Fair", unname(round(summary(q3.4)$tTable[-1, ], 3)))
tableprint[6, ] = c("Exams to Assignments", unname(round(summary(q3.9)$tTable[-1, ], 3)))
tableprint[7, ] = c("Exams to Grade", unname(round(summary(q3.15)$tTable[-1, ], 3)))
tableprint[8, ] = c("Fair to Assignments", unname(round(summary(q4.9)$tTable[-1, ], 3)))
tableprint[9, ] = c("Fair to Grade", unname(round(summary(q4.15)$tTable[-1, ], 3)))
tableprint[10, ] = c("Assignments to Grade", unname(round(summary(q9.15)$tTable[-1, ], 3)))

tableprint[11, ] = c("Overall to Exams", unname(round(summary(q1.3c)$tTable[-1, ], 3)))
tableprint[12, ] = c("Overall to Fair", unname(round(summary(q1.4c)$tTable[-1, ], 3)))
tableprint[13, ] = c("Overall to Assignments", unname(round(summary(q1.9c)$tTable[-1, ], 3)))
tableprint[14, ] = c("Overall to Grade", unname(round(summary(q1.15c)$tTable[-1, ], 3)))
tableprint[15, ] = c("Exams to Fair", unname(round(summary(q3.4c)$tTable[-1, ], 3)))
tableprint[16, ] = c("Exams to Assignments", unname(round(summary(q3.9c)$tTable[-1, ], 3)))
tableprint[17, ] = c("Exams to Grade", unname(round(summary(q3.15c)$tTable[-1, ], 3)))
tableprint[18, ] = c("Fair to Assignments", unname(round(summary(q4.9c)$tTable[-1, ], 3)))
tableprint[19, ] = c("Fair to Grade", unname(round(summary(q4.15c)$tTable[-1, ], 3)))
tableprint[20, ] = c("Assignments to Grade", unname(round(summary(q9.15c)$tTable[-1, ], 3)))

apa_table(tableprint,
          align = c("l", rep("c", 5)), 
          caption = "t Statistics for Undergraduate Correlations"
 )
```

## Instructor and Student Ratings
```{r instructor-ratings, include=FALSE}
correctedcourse = reliability[reliability$Course1 %in% c("101", "121"), ]
table(correctedcourse$type)
sum(table(correctedcourse$type))
temp = unique(correctedcourse[ , c("instructcode", "type")])
table(temp$type)
sum(table(temp$type))

library(nlme)
correctedcourse = subset(correctedcourse, type != is.na(type))
#overallscore
overallscore = lme(Q11 ~ type, 
             data = correctedcourse, 
             method = "ML", 
             na.action = "na.omit",
             random = ~1|instructcode)
summary(overallscore)

#exams match assignments
examsmatch = lme(Q31 ~ type, 
                   data = correctedcourse, 
                   method = "ML", 
                   na.action = "na.omit",
                   random = ~1|instructcode)
summary(examsmatch)

#grading is fair
fairgrading = lme(Q41 ~ type, 
                 data = correctedcourse, 
                 method = "ML", 
                 na.action = "na.omit",
                 random = ~1|instructcode)
summary(fairgrading)

#assignments are appropriate
assignappropriate = lme(Q91 ~ type, 
                  data = correctedcourse, 
                  method = "ML", 
                  na.action = "na.omit",
                  random = ~1|instructcode)
summary(assignappropriate)

#grade student will make
expectedgrade = lme(Q151 ~ type, 
                        data = correctedcourse, 
                        method = "ML", 
                        na.action = "na.omit",
                        random = ~1|instructcode)
summary(expectedgrade)


####Means & SDs for Corrected Course####
names(correctedcourse)
##Q11 = overall score
##Q31 = exams match assignments
##Q41 = grading is fair
##Q91 = assignments are appropriate
##Q151 = expected grade
##Type 1 = Graduate Student
##Type 2 = Per course Instructor
##Type 3 = Instructor
##Type 4 = Ranked Faculty

#overall score
tapply(correctedcourse$Q11, correctedcourse$type, mean)
tapply(correctedcourse$Q11, correctedcourse$type, sd)

#exams match assignments
tapply(correctedcourse$Q31, correctedcourse$type, mean)
tapply(correctedcourse$Q31, correctedcourse$type, sd)

#grading is fair
tapply(correctedcourse$Q41, correctedcourse$type, mean)
tapply(correctedcourse$Q41, correctedcourse$type, sd)

#assignments are appropriate
tapply(correctedcourse$Q91, correctedcourse$type, mean)
tapply(correctedcourse$Q91, correctedcourse$type, sd)

#expected grade
tapply(correctedcourse$Q151, correctedcourse$type, mean)
tapply(correctedcourse$Q151, correctedcourse$type, sd)

```

## Tables for Instructor Status
```{r Table-3, echo=FALSE, results='asis'}
tableprint = matrix(NA, nrow = 15, ncol = 5)
colnames(tableprint) = c("*b*", "*SE*", "*df*", "*t*", "*p*")

tableprint[1:3, ] = unname(round(summary(overallscore)$tTable[-1, ], 3))
tableprint[4:6, ] = unname(round(summary(examsmatch)$tTable[-1, ], 3))
tableprint[7:9, ] = unname(round(summary(fairgrading)$tTable[-1, ], 3))
tableprint[10:12, ] = unname(round(summary(assignappropriate)$tTable[-1, ], 3))
tableprint[13:15, ] = unname(round(summary(expectedgrade)$tTable[-1, ], 3))

tableprint = cbind(
  "DV" = c(rep("Overall Score", 3), 
           rep("Exams Match", 3), 
           rep("Fair Grading", 3), 
           rep("Appropriate Assignments", 3), 
           rep("Expected Grade", 3)),
  "Comparison Group" = c(rep(c("Teaching Assistant", "Per-Course Faculty", "Instructor"), 5)),
  tableprint)

apa_table(tableprint,
          align = c("l", "l", rep("c", 5)), 
          caption = "t Statistics for Instructor Status and Ratings"
 )
```

## Moderated Mediation

```{r mod-med, include=FALSE}
####Moderated Mediation Analysis from Model 3####
reliability$SCQ151 = scale(reliability$Q151, scale = F)
reliability$SCaveragegrade = scale(reliability$averagegrade, scale = F)

##X = Q151
##Y = Q11
##Mediator = Average Grade
##Moderator = Type 
##path c 
model3.1 = lme(Q11 ~ SCQ151*type, 
               data = reliability, 
               method = "ML", 
               na.action = "na.omit",
               random = ~1|instructcode)
summary(model3.1)

##path a
##average grade should not be scaled here
model3.2 = lme(averagegrade ~ SCQ151*type, 
               data = reliability, 
               method = "ML", 
               na.action = "na.omit",
               random = ~1|instructcode)
summary(model3.2)

##path b, c'
model3.3 = lme(Q11 ~ SCQ151*type + SCaveragegrade*type, 
               data = reliability, 
               method = "ML", 
               na.action = "na.omit",
               random = ~1|instructcode)
summary(model3.3)

####split type into four mediation MLMs####

##subset column 'type'
##Type 1 Data--Grad
type1data = subset(reliability, type == "1")
##Type2- Per Course
type2data = subset(reliability, type == "2")
##Type3 - Instructor
type3data = subset(reliability, type == "3")
##Type4 - Ranked Faculty
type4data = subset(reliability, type == "4")

##Type 1 Data--Grad
##path c 
model3.11 = lme(Q11 ~ SCQ151, 
               data = type1data, 
               method = "ML", 
               na.action = "na.omit",
               random = ~1|instructcode)
summary(model3.11)

##path a
##average grade should not be scaled here
model3.21 = lme(averagegrade ~ SCQ151, 
               data = type1data, 
               method = "ML", 
               na.action = "na.omit",
               random = ~1|instructcode)
summary(model3.21)

##path b, c'
model3.31 = lme(Q11 ~ SCQ151 + SCaveragegrade, 
               data = type1data, 
               method = "ML", 
               na.action = "na.omit",
               random = ~1|instructcode)
summary(model3.31)

#aroian sobel
a = coef(model3.21)[1,2]
b = coef(model3.31)[1,3]
SEa = summary(model3.21)$tTable[2,2]
SEb = summary(model3.31)$tTable[3,2]
zscore =  (a*b)/(sqrt((b^2*SEa^2)+(a^2*SEb^2)+(SEa*SEb)))
zscore
options(scipen = 999) ##turning off sci. not.
pnorm(abs(zscore), lower.tail = F)*2

#confidence intervals
total = coef(model3.11)[1,2] #cpath
direct = coef(model3.31)[1,2] #c' path
indirect = a*b
##this is the same thing as a*b

total; direct; indirect

####Bootstrapping the Mediation Effect####
##write a function that gives you the numbers you want
##we want the indirect effect
indirectsaved = function(dataset, random) {
  d = dataset[random, ] #randomize by row
  apath = lme(averagegrade ~ SCQ151, 
                  data = d, 
                  method = "ML", 
                  na.action = "na.omit",
                  random = ~1|instructcode)
  bpath = lme(Q11 ~ SCQ151 + SCaveragegrade, 
                  data = d, 
                  method = "ML", 
                  na.action = "na.omit",
                  random = ~1|instructcode)
  indirect = coef(apath)[1,2] * coef(bpath)[1,3]
  return(indirect)
}

library(boot)
##change nsims to lower so it knits, use 5000 for manuscript
#nsims = 5000
nsims = 10
bootresults = boot(data = type1data,
                   statistic = indirectsaved,
                   R = nsims)

bootresults
boot.ci(bootresults,
        conf = .95,
        type = "norm")

##Type2- Per Course
##path c 
model3.12 = lme(Q11 ~ SCQ151, 
                data = type2data, 
                method = "ML", 
                na.action = "na.omit",
                random = ~1|instructcode)
summary(model3.12)

##path a
##average grade should not be scaled here
model3.22 = lme(averagegrade ~ SCQ151, 
                data = type2data, 
                method = "ML", 
                na.action = "na.omit",
                random = ~1|instructcode)
summary(model3.22)

##path b, c'
model3.32 = lme(Q11 ~ SCQ151 + SCaveragegrade, 
                data = type2data, 
                method = "ML", 
                na.action = "na.omit",
                random = ~1|instructcode)
summary(model3.32)

#aroian sobel
a2 = coef(model3.22)[1,2]
b2 = coef(model3.32)[1,3]
SEa2 = summary(model3.22)$tTable[2,2]
SEb2 = summary(model3.32)$tTable[3,2]
zscore2 =  (a2*b2)/(sqrt((b2^2*SEa2^2)+(a2^2*SEb2^2)+(SEa2*SEb2)))
zscore2
pnorm(abs(zscore2), lower.tail = F)*2

#confidence intervals
total2 = coef(model3.12)[1,2] #cpath
direct2 = coef(model3.32)[1,2] #c' path
indirect2 = a2*b2
##this is the same thing as a*b

total2; direct2; indirect2


bootresults2 = boot(data = type2data,
                   statistic = indirectsaved,
                   R = nsims)

bootresults2
boot.ci(bootresults2,
        conf = .95,
        type = "norm")

##Type3 - Instructor
##path c 
model3.13 = lme(Q11 ~ SCQ151, 
                data = type3data, 
                method = "ML", 
                na.action = "na.omit",
                random = ~1|instructcode)
summary(model3.13)

##path a
##average grade should not be scaled here
model3.23 = lme(averagegrade ~ SCQ151, 
                data = type3data, 
                method = "ML", 
                na.action = "na.omit",
                random = ~1|instructcode)
summary(model3.23)

##path b, c'
model3.33 = lme(Q11 ~ SCQ151 + SCaveragegrade, 
                data = type3data, 
                method = "ML", 
                na.action = "na.omit",
                random = ~1|instructcode)
summary(model3.33)

#aroian sobel
a3 = coef(model3.23)[1,2]
b3 = coef(model3.33)[1,3]
SEa3 = summary(model3.23)$tTable[2,2]
SEb3 = summary(model3.33)$tTable[3,2]
zscore3 =  (a3*b3)/(sqrt((b3^2*SEa3^2)+(a3^2*SEb3^2)+(SEa3*SEb3)))
zscore3
pnorm(abs(zscore3), lower.tail = F)*2

#confidence intervals
total3 = coef(model3.13)[1,2] #cpath
direct3 = coef(model3.33)[1,2] #c' path
indirect3 = a3*b3
##this is the same thing as a*b

total3; direct3; indirect3


bootresults3 = boot(data = type3data,
                    statistic = indirectsaved,
                    R = nsims)

bootresults3
boot.ci(bootresults3,
        conf = .95,
        type = "norm")

##Type4 - Ranked Faculty
##path c 
model3.14 = lme(Q11 ~ SCQ151, 
                data = type4data, 
                method = "ML", 
                na.action = "na.omit",
                random = ~1|instructcode)
summary(model3.14)

##path a
##average grade should not be scaled here
model3.24 = lme(averagegrade ~ SCQ151, 
                data = type4data, 
                method = "ML", 
                na.action = "na.omit",
                random = ~1|instructcode)
summary(model3.24)

##path b, c'
model3.34 = lme(Q11 ~ SCQ151 + SCaveragegrade, 
                data = type4data, 
                method = "ML", 
                na.action = "na.omit",
                random = ~1|instructcode)
summary(model3.34)

#aroian sobel
a4 = coef(model3.24)[1,2]
b4 = coef(model3.34)[1,3]
SEa4 = summary(model3.24)$tTable[2,2]
SEb4 = summary(model3.34)$tTable[3,2]
zscore4 =  (a4*b4)/(sqrt((b4^2*SEa4^2)+(a4^2*SEb4^2)+(SEa4*SEb4)))
zscore4
pnorm(abs(zscore4), lower.tail = F)*2

#confidence intervals
total4 = coef(model3.14)[1,2] #cpath
direct4 = coef(model3.34)[1,2] #c' path
indirect4 = a4*b4
##this is the same thing as a*b

total4; direct4; indirect4


bootresults4 = boot(data = type4data,
                    statistic = indirectsaved,
                    R = nsims)

bootresults4
boot.ci(bootresults4,
        conf = .95,
        type = "norm")
```

##Table for Moderation Mediation Effects
```{r Table-4, echo=FALSE, results='asis'}
tableprint = matrix(NA, nrow = 25, ncol = 5)
colnames(tableprint) = c("*b*", "*SE*", "*df*", "*t*", "*p*")

tableprint[1:7, ] = unname(round(summary(model3.1)$tTable[-1, ], 3))
tableprint[8:14, ] = unname(round(summary(model3.2)$tTable[-1, ], 3))
tableprint[15:25, ] = unname(round(summary(model3.3)$tTable[-1, ], 3))

tableprint = cbind(
  "DV" = c(rep("Overall Course", 7),
           rep("Average Grading", 7),
           rep("Overall Course", 11)),
  "IV" = c("Expected Grade", "Teaching Assistant", "Per-Course", "Instructor",
           "EG X TA", "EG X PC", "EG X IN", 
           "Expected Grade", "Teaching Assistant", "Per-Course", "Instructor",
           "EG X TA", "EG X PC", "EG X IN",
           "Expected Grade", "Teaching Assistant", "Per-Course", "Instructor", 
           "Average Gradding", "EG X TA", "EG X PC", "EG X IN", 
           "AG X TA", "AG X PC", "AG X IN"),
  tableprint)

apa_table(tableprint,
          align = c("l", "l", rep("c", 5)), 
          caption = "t Statistics for Moderated Mediation"
 )
```

##Table for Each Type of Instructor
```{r Table-5, echo=FALSE, results='asis'}
tableprint = matrix(NA, nrow = 16, ncol = 5)
colnames(tableprint) = c("*b*", "*SE*", "*df*", "*t*", "*p*")

tableprint[1, ] = unname(round(summary(model3.11)$tTable[-1, ], 3))
tableprint[2, ] = unname(round(summary(model3.21)$tTable[-1, ], 3))
tableprint[3:4, ] = unname(round(summary(model3.31)$tTable[-1, ], 3))

tableprint[5, ] = unname(round(summary(model3.12)$tTable[-1, ], 3))
tableprint[6, ] = unname(round(summary(model3.22)$tTable[-1, ], 3))
tableprint[7:8, ] = unname(round(summary(model3.32)$tTable[-1, ], 3))

tableprint[9, ] = unname(round(summary(model3.13)$tTable[-1, ], 3))
tableprint[10, ] = unname(round(summary(model3.23)$tTable[-1, ], 3))
tableprint[11:12, ] = unname(round(summary(model3.33)$tTable[-1, ], 3))

tableprint[13, ] = unname(round(summary(model3.14)$tTable[-1, ], 3))
tableprint[14, ] = unname(round(summary(model3.24)$tTable[-1, ], 3))
tableprint[15:16, ] = unname(round(summary(model3.34)$tTable[-1, ], 3))

tableprint = cbind(
  "Group" = c(rep("Teaching Assistant", 4), 
              rep("Per-Course", 4),
              rep("Instructor", 4),
              rep("Ranked Faculty", 4)),
  "DV" = c("Overall Course", "Average Grading", "Overall Course", "Overall Course"),
  "IV" = c("Expected Grade", "Expected Grade", "Expected Grade", "Average Grading"),
tableprint
)

apa_table(tableprint,
          align = c("l", "l", "l", rep("c", 5)), 
          caption = "t Statistics for Individual Mediations"
 )
```