---
title: "Bootstrapped RQ1"
author: "Erin M. Buchanan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
# Seed for random number generation
set.seed(89432289)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
library(rio)
library(dplyr)
library(nlme)
library(effectsize)
library(ggplot2)
library(ppcor)
library(MuMIn)
library(papaja)

num_boots <- 3
```

## Data Source

```{r import-data}
# please note the data is deidentified but timing and course number is accurate
DF <- import("./data/final_evals.csv")

# we will only use courses with at least 15 ratings ... look at the paper that may be reliable (2013)
DF_sample <- DF %>% 
  filter(People >= 15)

# for this pre-reg we will randomly sample 20 percent of instructors 
# random_sample <- sample(unique(DF_sample$instructor_code), 
#                         size = round(length(unique(DF_sample$instructor_code)) * .30),
#                         replace = FALSE)
# 
# DF_sample <- DF_sample %>% 
#   filter(instructor_code %in% random_sample)
```

## RQ 1

During testing, we determined that bootstrapping this analysis would take several weeks of computation time. Therefore, we did not bootstrap this analysis. 

```{r rq1-nlme}
save_betas <- list()

# create matched dataframe
# let's see if twitter can help here - yes! @smartin2018 for the win!

# create unique id
DF_sample$evalid <- 1:nrow(DF_sample)

# create every pairwise combination 
combns <- t(combn(DF_sample$evalid,2))

# create a dataframe to hold that information, remove other frame for the love of space
longrel <- data.frame(evalid=combns[,1],evalid2=combns[,2]); rm(combns)

# add person 1 information back to dataframe
templong <- merge(longrel, DF_sample, by = "evalid")
colnames(templong)[1:2] <- c("evalid1", "evalid")

# add person 2 information back to the dataframe, remove other frame for the love of space
longrel <- merge(templong, DF_sample, by = "evalid")
rm(templong)

# create factors
longrel$instructormatch <- as.numeric(longrel$instructor_code.x == longrel$instructor_code.y)
longrel$semestermatch <- as.numeric(longrel$semester_count.x == longrel$semester_count.y)
longrel$coursematch <- as.numeric(longrel$new_course.x == longrel$new_course.y)

# boot strap the longrel
for (i in 1:num_boots){
   DF_boot <- longrel %>% 
     group_by(instructormatch, semestermatch, coursematch) %>% 
     slice_sample(n = nrow(longrel), replace = TRUE)
  
  #look at the contingency table
  #table(longrel$instructormatch, longrel$semestermatch, longrel$coursematch)
  
  # dataframe to put stuff in ----
  betarel <- matrix(NA, nrow = 2*2*2*2, ncol = 4+3)
  
  # going to let these overwrite each other so memory isn't bonkers
  # semester, course, instructor
  ## same same same ----
  tryCatch(                       
  expr = {                      
    relq1 <- lme(Q1AVG.y ~ Q1AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 1 & 
                               DF_boot$coursematch == 1 & 
                               DF_boot$instructormatch == 1, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y),
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq1)
  betarel[1 , ] <- c(1,1,1,"Overall", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq1)
  },
  error = function(e){
    betarel[1 , ] <- c(1,1,1,"Overall", NA, NA, NA)
  })
  
    tryCatch(                       
  expr = {                      
    relq4 <- lme(Q4AVG.y ~ Q4AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 1 & 
                               DF_boot$coursematch == 1 & 
                               DF_boot$instructormatch == 1, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq4)
  betarel[2 , ] <- c(1,1,1,"Fair", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq4)
  },
  error = function(e){
    betarel[1 , ] <- c(1,1,1,"Fair", NA, NA, NA)
  })
  
  ## same same different ----
  tryCatch(                       
  expr = {                      
      relq1 <- lme(Q1AVG.y ~ Q1AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 1 & 
                               DF_boot$coursematch == 1 & 
                               DF_boot$instructormatch == 0, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq1)
  betarel[3 , ] <- c(1,1,0,"Overall", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq1)
  },
  error = function(e){
    betarel[3 , ] <- c(1,1,0,"Overall", NA, NA, NA)
  })
  
  tryCatch(                       
  expr = {                      
    relq4 <- lme(Q4AVG.y ~ Q4AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 1 & 
                               DF_boot$coursematch == 1 & 
                               DF_boot$instructormatch == 0, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq4)
  betarel[4 , ] <- c(1,1,0,"Fair", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq4)
  },
  error = function(e){
    betarel[4 , ] <- c(1,1,0,"Fair", NA, NA, NA)
  })
  

  
  
  
  ## same different same ----
  tryCatch(                       
  expr = {                      
      relq1 <- lme(Q1AVG.y ~ Q1AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 1 & 
                               DF_boot$coursematch == 0 & 
                               DF_boot$instructormatch == 1, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq1)
  betarel[5 , ] <- c(1,0,1,"Overall", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq1)
  },
  error = function(e){
    betarel[5 , ] <- c(1,0,1,"Overall", NA, NA, NA)
  })
  
  tryCatch(                       
  expr = {                      
    relq4 <- lme(Q4AVG.y ~ Q4AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 1 & 
                               DF_boot$coursematch == 0 & 
                               DF_boot$instructormatch == 1, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq4)
  betarel[6 , ] <- c(1,0,1,"Fair", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq4)
  },
  error = function(e){
    betarel[6 , ] <- c(1,0,1,"Fair", NA, NA, NA)
  })
  
  ## same different different ----
  tryCatch(                       
  expr = {                      
      relq1 <- lme(Q1AVG.y ~ Q1AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 1 & 
                               DF_boot$coursematch == 0 & 
                               DF_boot$instructormatch == 0, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq1)
  betarel[7 , ] <- c(1,0,0,"Overall", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq1)
  },
  error = function(e){
    betarel[7 , ] <- c(1,0,0,"Overall", NA, NA, NA)
  })
  
  tryCatch(                       
  expr = {                      
    relq4 <- lme(Q4AVG.y ~ Q4AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 1 & 
                               DF_boot$coursematch == 0 & 
                               DF_boot$instructormatch == 0, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq4)
  betarel[8 , ] <- c(1,0,0,"Fair", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq4)
  },
  error = function(e){
    betarel[8 , ] <- c(1,0,0,"Fair", NA, NA, NA)
  })
  
  ## different different different ----
  tryCatch(                       
  expr = {                      
    relq1 <- lme(Q1AVG.y ~ Q1AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 0 & 
                               DF_boot$coursematch == 0 & 
                               DF_boot$instructormatch == 0, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq1)
  betarel[9 , ] <- c(0,0,0,"Overall", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq1)
  },
  error = function(e){
    betarel[9 , ] <- c(0,0,0,"Overall", NA, NA, NA)
  })
  
  tryCatch(                       
  expr = {                      
    relq4 <- lme(Q4AVG.y ~ Q4AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 0 & 
                               DF_boot$coursematch == 0 & 
                               DF_boot$instructormatch == 0, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq4)
  betarel[10 , ] <- c(0,0,0,"Fair", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq4)
  },
  error = function(e){
    betarel[10 , ] <- c(0,0,0,"Fair", NA, NA, NA)
  })
  
  ## different same different ----
  tryCatch(                       
  expr = {                      
    relq1 <- lme(Q1AVG.y ~ Q1AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 0 & 
                               DF_boot$coursematch == 1 & 
                               DF_boot$instructormatch == 0, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq1)
  betarel[11 , ] <- c(0,1,0,"Overall", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq1)
  },
  error = function(e){
    betarel[11 , ] <- c(0,1,0,"Overall", NA, NA, NA)
  })
  
  tryCatch(                       
  expr = {                      
    relq4 <- lme(Q4AVG.y ~ Q4AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 0 & 
                               DF_boot$coursematch == 1 & 
                               DF_boot$instructormatch == 0, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq4)
  betarel[12 , ] <- c(0,1,0,"Fair", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq4)
  },
  error = function(e){
    betarel[12 , ] <- c(0,1,0,"Fair", NA, NA, NA)
  })
  
  ## different different same ----
  tryCatch(                       
  expr = {                      
      relq1 <- lme(Q1AVG.y ~ Q1AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 0 & 
                               DF_boot$coursematch == 0 & 
                               DF_boot$instructormatch == 1, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq1)
  betarel[13 , ] <- c(0,0,1,"Overall", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq1)
  },
  error = function(e){
    betarel[13 , ] <- c(0,0,1,"Overall", NA, NA, NA)
    })
  
  tryCatch(                       
  expr = {                      
    relq4 <- lme(Q4AVG.y ~ Q4AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 0 & 
                               DF_boot$coursematch == 0 & 
                               DF_boot$instructormatch == 1, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq4)
  betarel[14 , ] <- c(0,0,1,"Fair", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq4)
  },
  error = function(e){
    betarel[14 , ] <- c(0,0,1,"Fair", NA, NA, NA)
  })
  
  ## different same same ----
  tryCatch(                       
  expr = {                      
     relq1 <- lme(Q1AVG.y ~ Q1AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 0 & 
                               DF_boot$coursematch == 1 & 
                               DF_boot$instructormatch == 1, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq1)
  betarel[15 , ] <- c(0,1,1,"Overall", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq1)
  
  },
  error = function(e){
    betarel[15 , ] <- c(0,1,1,"Overall", NA, NA, NA)
  })
  
  tryCatch(                       
  expr = {                      
      relq4 <- lme(Q4AVG.y ~ Q4AVG.x + People.x + People.y, 
             data = DF_boot[ DF_boot$semestermatch == 0 & 
                               DF_boot$coursematch == 1 & 
                               DF_boot$instructormatch == 1, ], 
             method = "ML", 
             na.action = "na.omit",
             random = list(~1|instructor_code.x, ~1|instructor_code.y), 
             control = lmeControl(opt = "optim"))
  temp <- standardize_parameters(relq4)
  betarel[16 , ] <- c(0,1,1,"Fair", temp$Std_Coefficient[2], temp$CI_low[2], temp$CI_high[2])
  rm(relq4)

  betarel <- as.data.frame(betarel)
  colnames(betarel) <- c("Semester", "Course", "Instructor", "Question",
                        "b", "CI_Low", "CI_High")
  },
  error = function(e){
    betarel[16 , ] <- c(0,1,1,"Fair", NA, NA, NA)
  })

  save_betas[[i]] <- betarel
}
```

## Figure 1

```{r figure1, include = TRUE, fig.cap= "Reliability estimates for instructor, course, and semester combinations."}
betarel$b <- as.numeric(betarel$b)
betarel$CI_Low <- as.numeric(betarel$CI_Low)
betarel$CI_High <- as.numeric(betarel$CI_High)
betarel$Semester_nice <- factor(betarel$Semester, 
                           levels = c(0,1),
                           labels = c("Different", "Same"))
betarel$Instructor_nice <- factor(betarel$Instructor, 
                           levels = c(0,1),
                           labels = c("Different Instructor", "Same Instructor"))
betarel$Course_nice <- factor(betarel$Course, 
                           levels = c(0,1),
                           labels = c("Different Course", "Same Course"))

write.csv(betarel, "../output/beta_values_rq1_boot.csv", row.names = F)

ggplot(betarel, aes(Semester_nice, b, color = Course_nice)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = CI_Low, ymax = CI_High), width = 0.2) + 
  theme_classic() + 
  facet_grid(Question~Instructor_nice) + 
  ylab("Reliability") + 
  xlab("Semester Match") + 
  scale_color_discrete(name = "Course Match")

ggsave("../output/figure1_boot.png")
```